### PR TITLE
Chart.js 2

### PR DESCRIPTION
**Pull request by joris-lambrechts**
Hi,

I made an attempt to update Chart.js to version 2

- Source updates are rather limited
- Tests are adapted and added some more for other cases
- Demo's are adapted to match the same look and feel of version 1.0.x. For the Line chart demo I also added the dynamic update of data as shown in the Chart.js samples

In case of bugs, suggestions, ... let me know

Kind regards,
Joris

### CODE REVIEW

**Comment by carlcraig** [comment]
Thanks for putting this PR together :+1: 

I will take a look through everything and hopefully get it merged in the next few days.

**Comment by joris-lambrechts** [comment]
I noticed that the [doughnut example page](https://github.com/joris-lambrechts/tc-angular-chartjs/blob/chartjs2.0/demo/doughnut/index.html) is missing the JavaScript (it says `TODO`). I'm currently facing problems with pushing the commit for this to github

**Comment by carlcraig** [comment]
I am going to branch the existing master into a `1.x` branch, will then merge this into master.

Everything looks ok for me to merge, we can work on the examples/docs after?

Is there anything else you want to add to this PR?

**Comment by joris-lambrechts** [comment]
No, I think it is sufficient.

**Comment by carlcraig** [comment]
Thanks for this contribution :+1: 

I have published new v2.0.0 https://github.com/carlcraig/tc-angular-chartjs/releases/tag/v2.0.0 and also on npm.

**Comment by joris-lambrechts** [comment]
You're welcome! :)

**Pull request merged**
