### PR TITLE
Added click support on chart data

### PR DESCRIPTION
**Pull request by cstefanache**

### CODE REVIEW

**Comment by ducpham-asnet** [comment]
`getSegmentsAtEvent` is not available for Line and Radar charts.

**Comment by cstefanache** [comment]
Added support for line, radar and bars. Checked if functions exists rather than type checking in order to avoid string type equals.

**Comment by ducpham-asnet** [comment]
Great. But it seems to be you missed changes for dist file.

**Comment by cstefanache** [comment]
Dist package built. At the moment the onclick function is assigned using & isolated scope - the listener will be attached on each chart because of the wrapping function. It can be changed to = if required

**Comment by ducpham-asnet** [comment]
@carlcraig Could you help to review this MR?

**Comment by carlcraig** [comment]
Looks good, will publish a release soon.

**Comment by carlcraig** [comment]
Published version `1.0.13`, thanks for the contribution :+1:

**Pull request merged**
