### PR TITLE
CommonJS Support

### PR DESCRIPTION
**Pull request by seanhealy**
As per the new Angular Common JS style.
https://www.npmjs.com/package/angular-animate

### CODE REVIEW

**Comment by carlcraig** [comment]
Thanks,
All looks good.

**Comment by carlcraig** [comment]
I will publish this to npm at some point and bump the version.

**Comment by seanhealy** [comment]
Thanks!

**Comment by carlcraig** [comment]
@seanhealy have published this on npm now, please let me know if there are any issues.

**Comment by seanhealy** [comment]
Thanks again!

**Pull request merged**
